name = "spinmacho-app-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmacho-app.com.gr"
HMAC_KEY = "99893b746e8354f00eae39303172494b5c6be8c1223ee27fb243a5d6f6301b45"
COOKIE_NAME = "8sh"
PLAY_PATH = "visit-site"
BUTTON_ID = "p7a48998f1d3121b977b99bc2c0481ac6"
GATE_SALT = "1365db04b5e8fe45"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "8wq2"
CTA_SELECTOR = ".play-button"
